name: Update Charts
on:
    workflow_dispatch:
        inputs:
            chart:
                type: choice
                description: Choose a chart for update.
                options: 
                - robot-operator
                - fleet-operator
                - connection-hub-operator
            version:
                type: string
                required: true
                description: 'App version of the chart.'

env:
    CHART_DIR: ./charts/

permissions:
    contents: write

jobs:
    generate:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v3
            with:
                ref: ${{ github.head_ref }}
          - name: Release name
            run: |
                set -eux;
                cd ${{ env.CHART_DIR }};
                rm ${{ github.event.inputs.chart }};
                git clone --depth 1 --branch ${{ github.event.inputs.version }} --no-checkout https://github.com/robolaunch/${{ github.event.inputs.chart }}.git;
                cd robot-operator;
                git sparse-checkout set hack/deploy/chart/${{ github.event.inputs.chart }};
                git checkout ${{ github.event.inputs.version }};
                rm .git;
          - uses: stefanzweifel/git-auto-commit-action@v4
            with:
                commit_message: "bump(charts): bump ${{ github.event.inputs.chart }} chart to ${{ github.event.inputs.version }}"